#!/usr/bin/env python3
"""Reproduce the u8i8 HTP prepare bias-sidecar probes.

This example isolates the path:

    float Conv(A,W,B) -> quantized DLC static B -> HTP prepare bias_to_vtcm

It does not run the device.  The current mismatch is already visible in the
context binary generated by qnn-context-binary-generator.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.analyze_u8i8_native_bias_record import (  # noqa: E402
    ACT_ZP,
    expected_record,
    extract_dlc_bias,
    find_native_record,
    load_case,
    parse_record,
)


VECTOR_BIASES = np.array(
    [
        -1024,
        -900,
        -800,
        -720,
        -670,
        -660,
        -453,
        -330,
        -117,
        -14,
        -3,
        -1,
        0,
        1,
        2,
        3,
        14,
        117,
        175,
        597,
        650,
        660,
        670,
        690,
        720,
        800,
        900,
        1024,
        1500,
        -1500,
        2047,
        -2047,
    ],
    dtype=np.int32,
)


def run(cmd: list[str], *, log: Path | None = None, env: dict[str, str] | None = None) -> None:
    if log is None:
        subprocess.run(cmd, cwd=REPO_ROOT, env=env, check=True)
        return
    log.parent.mkdir(parents=True, exist_ok=True)
    with log.open("w", encoding="utf-8") as f:
        subprocess.run(cmd, cwd=REPO_ROOT, env=env, stdout=f, stderr=subprocess.STDOUT, check=True)


def qnn_python_env(qnn_sdk_root: Path) -> dict[str, str]:
    env = os.environ.copy()
    py = str(qnn_sdk_root / "lib/python")
    env["PYTHONPATH"] = py + (":" + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    return env


def generate_base(out_root: Path, *, m: int, k: int, n: int, env: dict[str, str]) -> Path:
    run(
        [
            "uv",
            "run",
            "python",
            "scripts/generate_qnn_matmul_python_cases.py",
            "--out-root",
            str(out_root),
            "--m",
            str(m),
            "--k",
            str(k),
            "--n",
            str(n),
            "--families",
            "u8i8",
            "--cases",
            "normal_random",
        ],
        env=env,
        log=out_root / "_generate.log",
    )
    return out_root / "u8i8" / "normal_random"


def write_array(case_dir: Path, name: str, array: np.ndarray) -> None:
    np.save(case_dir / f"{name}.npy", array)
    array.reshape(-1).tofile(case_dir / f"{name}.raw")


def make_zero_sum_case(base_case: Path, case_dir: Path, *, case_name: str, bias_q: np.ndarray) -> None:
    if case_dir.exists():
        shutil.rmtree(case_dir)
    shutil.copytree(base_case, case_dir)
    meta = json.loads((case_dir / "case.json").read_text(encoding="utf-8"))
    m, k, n = [int(v) for v in meta["shape_mkn"]]
    if bias_q.shape != (n,):
        raise ValueError(f"{case_name}: bias shape {bias_q.shape} != N={n}")

    # Each output channel has sum_k(weight_q)=0.  This makes the final sidecar
    # effective-bias field equal to the prepared bias itself, so any delta is
    # caused by HTP prepare, not activation-zero-point folding.
    weight_q_nk = np.tile(np.array([64, -64], dtype=np.int8), (n, k // 2)).reshape(n, k)
    weight_scale = np.full((n,), np.float32(0.0078125), dtype=np.float32)
    weight_float_nk = weight_q_nk.astype(np.float32) * weight_scale[:, None]
    act_scale = np.float32(meta["qparams"]["activation"]["scale"])
    bias_float = (bias_q.astype(np.float32) * act_scale * weight_scale).astype(np.float32)

    write_array(case_dir, "weight_q_nk", weight_q_nk)
    write_array(case_dir, "weight_q_kn", weight_q_nk.T.copy())
    write_array(case_dir, "weight_scale", weight_scale)
    write_array(case_dir, "weight_float_nk", weight_float_nk)
    write_array(case_dir, "bias_q_int32", bias_q)
    write_array(case_dir, "bias_float", bias_float)

    meta["case"] = case_name
    meta["qparams"]["weight"]["scale"] = [float(v) for v in weight_scale]
    meta["qparams"]["bias"]["scale"] = [float(act_scale * v) for v in weight_scale]
    meta["qparams"]["bias"]["observed_min"] = float(bias_float.min())
    meta["qparams"]["bias"]["observed_max"] = float(bias_float.max())
    meta["probe_contract"] = {
        "weight_sum": "zero per output channel",
        "expected_effective_i32": "bias_q_int32 because -128*sum(weight_q)=0",
        "purpose": "separate HTP prepare bias conversion from activation-zero-point folding",
    }
    (case_dir / "case.json").write_text(json.dumps(meta, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def prepare_native(case_dir: Path, out_dir: Path, *, qnn_sdk_root: Path, env: dict[str, str]) -> None:
    run(
        [
            "uv",
            "run",
            "python",
            "scripts/run_qnn_python_case_native.py",
            "--case-dir",
            str(case_dir),
            "--out-dir",
            str(out_dir),
            "--qnn-sdk-root",
            str(qnn_sdk_root),
            "--no-device",
        ],
        env=env,
        log=out_dir.parent / f"{out_dir.name}.log",
    )


def counts(values: np.ndarray) -> dict[str, int]:
    unique, freq = np.unique(values, return_counts=True)
    return {str(int(v)): int(c) for v, c in zip(unique, freq)}


def analyze_case(case_dir: Path, native_dir: Path, analysis_dir: Path) -> dict[str, Any]:
    meta, expected, _, _, exp_eff = expected_record(case_dir)
    offset, native_record, candidates = find_native_record(native_dir / "ctx/case_native_ctx.bin", expected)
    exp_scale, exp_control, _ = parse_record(expected)
    nat_scale, nat_control, nat_eff = parse_record(native_record)
    _, weight_q_nk, bias_q, _, _, _ = load_case(case_dir)
    folded_i32 = (-ACT_ZP) * weight_q_nk.T.astype(np.int32).sum(axis=0).astype(np.int32)
    native_bias_q = (nat_eff - folded_i32).astype(np.int32)
    dlc_bias_q = extract_dlc_bias(native_dir / "case.dlc")

    analysis_dir.mkdir(parents=True, exist_ok=True)
    native_record.reshape(-1).tofile(analysis_dir / f"{meta['case']}.native_bias_record.raw")
    np.save(analysis_dir / f"{meta['case']}.native_bias_q.npy", native_bias_q)
    np.save(analysis_dir / f"{meta['case']}.dlc_bias_q.npy", dlc_bias_q)

    nonzero = np.flatnonzero(native_bias_q != dlc_bias_q)
    preview = [
        {
            "channel": int(i),
            "generated_bias_q": int(bias_q[i]),
            "dlc_bias_q": int(dlc_bias_q[i]),
            "native_sidecar_bias_q": int(native_bias_q[i]),
            "delta_native_minus_dlc": int(native_bias_q[i] - dlc_bias_q[i]),
        }
        for i in nonzero[:64]
    ]
    return {
        "case": meta["case"],
        "shape_mkn": meta["shape_mkn"],
        "case_dir": str(case_dir),
        "native_dir": str(native_dir),
        "native_record_offset": int(offset),
        "top_candidates": [
            {
                "score": int(score),
                "offset": int(off),
                "scale_match": int(scale_match),
                "control_match": int(control_match),
                "effective_close": int(eff_close),
            }
            for score, off, scale_match, control_match, eff_close in candidates
        ],
        "native_vs_generated_bytes": int((native_record == expected).sum()),
        "native_record_bytes": int(expected.size),
        "scale_match": int((nat_scale == exp_scale).sum()),
        "control_match": int((nat_control == exp_control).sum()),
        "effective_delta_counts": counts(nat_eff - exp_eff),
        "dlc_B_vs_generated_bias_q": counts(dlc_bias_q - bias_q),
        "native_sidecar_bias_q_vs_DLC_B": counts(native_bias_q - dlc_bias_q),
        "native_DLC_bias_nonzero_preview": preview,
        "conclusion": (
            "DLC B equals generated bias_q; native/DLC deltas first appear in HTP prepare "
            "and are reproduced by the recovered sidecar rule."
        ),
    }


def write_markdown_summary(path: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# Bias Prepare Probe Summary",
        "",
        f"Output root: `{summary['out_root']}`",
        "",
        "| Case | Shape | DLC B == generated | Native sidecar vs DLC B | Scale | Control |",
        "|---|---:|---|---|---:|---:|",
    ]
    for case in summary["cases"]:
        lines.append(
            "| {case} | {shape} | `{dlc}` | `{native}` | {scale}/{n} | {control}/{n} |".format(
                case=case["case"],
                shape="x".join(str(v) for v in case["shape_mkn"]),
                dlc=case["dlc_B_vs_generated_bias_q"],
                native=case["native_sidecar_bias_q_vs_DLC_B"],
                scale=case["scale_match"],
                control=case["control_match"],
                n=case["shape_mkn"][2],
            )
        )
    lines.extend(
        [
            "",
            "Current interpretation:",
            "",
            "- `qairt-quantizer` is not the source of the `+/-1` bias deltas.",
            "- The deltas are introduced by HTP prepare while constructing `bias_to_vtcm` "
            "and should match the recovered rule.",
            "- The zero-sum weights make folded activation zero-point contribution zero, "
            "so the probe isolates the bias conversion path.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-root", type=Path, default=Path("/tmp/qcom_htp_u8i8_bias_prepare_probe"))
    parser.add_argument("--qnn-sdk-root", type=Path, default=Path(os.environ.get("QNN_SDK_ROOT", "tools/qnn-sdk")))
    parser.add_argument(
        "--only",
        choices=["all", "vector32", "sweep160"],
        default="all",
        help="Limit the generated probes when iterating.",
    )
    args = parser.parse_args()

    out_root = args.out_root.resolve()
    if out_root.exists():
        shutil.rmtree(out_root)
    cases_root = out_root / "cases"
    native_root = out_root / "native"
    analysis_root = out_root / "analysis"
    env = qnn_python_env(args.qnn_sdk_root.resolve())
    qnn_py = args.qnn_sdk_root.resolve() / "lib/python"
    if str(qnn_py) not in sys.path:
        sys.path.insert(0, str(qnn_py))

    planned: list[tuple[str, int, np.ndarray]] = []
    if args.only in {"all", "vector32"}:
        planned.append(("zero_sum_vector32", 32, VECTOR_BIASES.copy()))
    if args.only in {"all", "sweep160"}:
        planned.append(("zero_sum_sweep160_m80_p79", 160, np.arange(-80, 80, dtype=np.int32)))

    reports = []
    for case_name, n, bias_q in planned:
        base_root = out_root / "base" / case_name
        base_case = generate_base(base_root, m=32, k=128, n=n, env=env)
        case_dir = cases_root / case_name
        native_dir = native_root / case_name
        make_zero_sum_case(base_case, case_dir, case_name=case_name, bias_q=bias_q)
        prepare_native(case_dir, native_dir, qnn_sdk_root=args.qnn_sdk_root.resolve(), env=env)
        reports.append(analyze_case(case_dir, native_dir, analysis_root))

    summary = {
        "schema": "qcom_htp.u8i8_bias_prepare_probe.v1",
        "out_root": str(out_root),
        "qnn_sdk_root": str(args.qnn_sdk_root.resolve()),
        "cases": reports,
        "status": "rule_recovered",
        "next_question": "use this probe as a regression check for the recovered HTP prepare bias rule",
    }
    analysis_root.mkdir(parents=True, exist_ok=True)
    (analysis_root / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_markdown_summary(analysis_root / "summary.md", summary)
    print(f"wrote {analysis_root / 'summary.json'}")
    print(f"wrote {analysis_root / 'summary.md'}")
    for case in reports:
        print(
            f"{case['case']}: DLC B delta {case['dlc_B_vs_generated_bias_q']} "
            f"native sidecar delta {case['native_sidecar_bias_q_vs_DLC_B']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
