#!/usr/bin/env python3
"""Emit an embeddable Hexagon inline-asm .byte body for an HMX kernel slice.

The owned u8i8 path eventually converted its byte replica to handwritten inline
asm.  The other quantized MatMul families start from exact native byte slices so
their descriptor/packing ABI can be validated before spending time naming every
packet.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


DEFAULT_SO = "tools/qnn-sdk/lib/hexagon-v75/unsigned/libQnnHtpV75Skel.so"
DEFAULT_NM = "llvm-nm"
DEFAULT_OBJDUMP = "llvm-objdump"


def _parse_int(value: str) -> int:
    return int(value, 0)


def _symbol_table(so: Path, nm: str) -> dict[str, tuple[int, int]]:
    out = subprocess.check_output(
        [nm, "-D", "--print-size", str(so)],
        text=True,
    )
    symbols: dict[str, tuple[int, int]] = {}
    line_re = re.compile(r"^([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+\S\s+(\S+)$")
    for line in out.splitlines():
        m = line_re.match(line.strip())
        if not m:
            continue
        symbols[m.group(3)] = (int(m.group(1), 16), int(m.group(2), 16))
    return symbols


def _disasm(so: Path, objdump: str, vma: int, size: int) -> dict[int, str]:
    out = subprocess.check_output(
        [
            objdump,
            "-d",
            f"--start-address=0x{vma:x}",
            f"--stop-address=0x{vma + size:x}",
            str(so),
        ],
        text=True,
        errors="replace",
    )
    info: dict[int, str] = {}
    line_re = re.compile(
        r"\s*([0-9a-fA-F]+):\s*"
        r"[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+[0-9a-fA-F]{2}\s+"
        r"[0-9a-fA-F]{8}\s+(.+)$"
    )
    for line in out.splitlines():
        m = line_re.match(line)
        if m:
            info[int(m.group(1), 16)] = m.group(2).rstrip()
    return info


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--so", default=DEFAULT_SO)
    ap.add_argument("--symbol", help="symbol name to extract")
    ap.add_argument("--vma", type=_parse_int, help="slice start virtual address/file offset")
    ap.add_argument("--size", type=_parse_int, help="slice size in bytes")
    ap.add_argument("--label", help="human-readable label for comments")
    ap.add_argument("--out", required=True)
    ap.add_argument("--nm", default=DEFAULT_NM)
    ap.add_argument("--objdump", default=DEFAULT_OBJDUMP)
    args = ap.parse_args()

    so = Path(args.so)
    if args.symbol:
        symbols = _symbol_table(so, args.nm)
        if args.symbol not in symbols:
            raise SystemExit(f"symbol not found: {args.symbol}")
        sym_vma, sym_size = symbols[args.symbol]
        vma = args.vma if args.vma is not None else sym_vma
        size = args.size if args.size is not None else sym_size
        label = args.label or args.symbol
    else:
        if args.vma is None or args.size is None:
            raise SystemExit("--vma and --size are required when --symbol is omitted")
        vma = args.vma
        size = args.size
        label = args.label or f"0x{vma:x}"

    if size <= 0 or size % 4:
        raise SystemExit(f"slice size must be a positive multiple of 4, got {size}")

    data = so.read_bytes()
    blob = data[vma:vma + size]
    if len(blob) != size:
        raise SystemExit(f"short read at 0x{vma:x}: got {len(blob)} expected {size}")

    asm = _disasm(so, args.objdump, vma, size)

    lines = [
        f"  /* {size} bytes -- exact byte replica of {so}",
        f"   * 0x{vma:x} `{label}`.",
        "   * One word per .byte directive; comments are decoded llvm-objdump",
        "   * lines where the public toolchain can decode them.",
        "   * Generated by scripts/extract_hmx_kernel_bytes.py. */",
    ]
    for off in range(0, size, 4):
        word = blob[off:off + 4]
        bs = ", ".join(f"0x{b:02x}" for b in word)
        addr = vma + off
        instr = asm.get(addr, "").replace("\\", "\\\\").replace('"', '\\"')
        comment = f" /* {addr:08x}: {instr} */" if instr else ""
        lines.append(f'  ".byte {bs}\\n"{comment}')

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({size} bytes / {size // 4} words from 0x{vma:x})")


if __name__ == "__main__":
    main()
